[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    hideakitai/MPU9250 @ ^0.4.8
    mikalhart/TinyGPSPlus @ ^1.1.0  ; Mantén esta si vas a usar el GPS
    